### ISSUE TITLE
Domain access for smb users

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [plesk/pm-docs#1]
Hi guys.

In our JXcore extension we're displaying a list of domains accessible per logged user. In case of client account this is easy and working, however for smb users became a little bit tricky if we would like to respect "Access to subscriptions" field's value (to display on domains list only the exact one).

![plesk-user](https://cloud.githubusercontent.com/assets/5946844/10515588/6c35ebbe-7354-11e5-8937-468aaf65981e.png) 

For Plesk 12 I was able to use `$_SESSION['auth']['smbUserId']` value, then read the user from MySQL `smb-users` table and that works fine. 
(BTW. I think `pm_Session::getClient()->hasAccessToDomain($domainId)` should be doing that, or maybe there is a need for `pm_Session::getUser()` if they should be deistinquished ?).

However for Plesk < 12 the above solution cannot be applied (there is no `$_SESSION['auth']`).

All I need for now is to get logged smb user ID. I guess `pm_Session::getImpersonatedClientId()` is not meant to give that, because it is `null`.

Other possible ways to use `pm_Session::getCurrentDomain()` or pass "dom_id" GET parameter will not be useful here.

**Comment by xgin** [comment]
Try the workaround for Plesk < 12: $_SESSION[session_id() . '_smb_user_id']

For the reference: we have created the issue in the internal tracker PPP-18144

**Comment by ktrzeciaknubisa** [comment]
Thank you, the workaround seems to work!
